apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-02-24T11:46:06Z"
  labels:
    app: app2
  name: app2
  namespace: default
  resourceVersion: "359065"
  uid: c6735ece-9eb7-4848-9dd2-9a11d426be76
spec:
  clusterIP: 10.105.109.78
  clusterIPs:
  - 10.105.109.78
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32473
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app2
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
