apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-02-24T11:45:53Z"
  labels:
    app: app1
  name: app1
  namespace: default
  resourceVersion: "359047"
  uid: 3756d389-45ed-4a11-a33e-799cf5f55ffc
spec:
  clusterIP: 10.101.107.164
  clusterIPs:
  - 10.101.107.164
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32594
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
