apiVersion : apps/v1
kind : Deployment
metadata : 
 name : nginx-deployment
spec :
 replicas : 5 
 selector : 
  matchLabels :
   app : nginx 
   provider : k8s
 template :
   metadata :
    labels :
     app : nginx
     provider : k8s
   spec :
    containers :
     - name : nginx
       image : nginx:1.14.2
       ports :
        - containerPort : 80