apiVersion : apps/v1
kind : Deployment
metadata : 
 name : test-deployment 
spec :
  replicas : 4
  strategy :
    type : RollingUpdate

  selector : 
    matchLabels :
      app : test
  template :
    metadata :
      labels :
        app : test
    spec :
      containers :
        - name : test
          image : moaaz17877640/nodejs-k8s:v1
          ports :
            - containerPort : 3000