apiVersion  : v1
kind: Pod
metadata :
  name : redis
spec :
  containers :
    - name : redis
      image : redis
      command : [ redis-server , "/redis-master/redis.conf" ]
      env :
      - name : MASTER
        value : "true"
      ports :
        - containerPort : 6379
      resources :
        requests :
          cpu : "0.1"
      volumeMounts :
        - name : data
          mountPath : /redis-master-data
        - name : config
          mountPath : /redis-master
  volumes :
    - name : data
      emptyDir : {}
    - name : config
      configMap :
        name : redis-configmap
        items :
          - key : redis-config
            path : redis.conf
